In [2]:
import pandas as pd

In [5]:
dados = {
    'Time' : ['Flamengo', 'São Paulo', 'Palmeiras', 'Santos', 'Corinthians'],
    'Partidas' : [10, 10, 10, 10, 10],
    'Vitorias': [7, 6, 5, 4, 3],
    'Empates': [2, 1, 3, 3, 2],
    'Derrotas': [1, 3, 2, 3, 5],
    'Gols_Pro': [22, 16, 18, 14, 10],
    'Gols_Contra': [10, 15, 12, 16, 20],
}
df = pd.DataFrame(dados)
df

          Time  Partidas  Vitorias  Empates  Derrotas  Gols_Pro  Gols_Contra
0     Flamengo        10         7        2         1        22           10
1    São Paulo        10         6        1         3        16           15
2    Palmeiras        10         5        3         2        18           12
3       Santos        10         4        3         3        14           16
4  Corinthians        10         3        2         5        10           20

In [7]:
df['Saldo_Gols'] = df['Gols_Pro'] - df['Gols_Contra']
df

,Time,Partidas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols
0,Flamengo,10,7,2,1,22,10,12
1,São Paulo,10,6,1,3,16,15,1
2,Palmeiras,10,5,3,2,18,12,6
3,Santos,10,4,3,3,14,16,-2
4,Corinthians,10,3,2,5,10,20,-10

In [9]:
df['Pontos'] = df['Vitorias'] * 3 + df['Empates'] * 1
df

,Time,Partidas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19
2,Palmeiras,10,5,3,2,18,12,6,18
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [12]:
df = df.sort_values(by='Pontos', ascending=False)
df

,Time,Partidas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19
2,Palmeiras,10,5,3,2,18,12,6,18
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [16]:
df.to_excel("dados/campeonato_brasileiro.xlsx", index=False)