In [2]:
import pandas as pd

In [4]:
df = pd.read_excel("dados/campeonato_brasileiro.xlsx")
df

,Time,Partidas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19
2,Palmeiras,10,5,3,2,18,12,6,18
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [11]:
df.describe()

,Partidas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
count,5.0,5.000000,5.00000,5.00000,5.000000,5.000000,5.000000,5.000000
mean,10.0,5.000000,2.20000,2.80000,16.000000,14.600000,1.400000,17.200000
std,0.0,1.581139,0.83666,1.48324,4.472136,3.847077,8.294577,4.494441
min,10.0,3.000000,1.00000,1.00000,10.000000,10.000000,-10.000000,11.000000
25%,10.0,4.000000,2.00000,2.00000,14.000000,12.000000,-2.000000,15.000000
50%,10.0,5.000000,2.00000,3.00000,16.000000,15.000000,1.000000,18.000000
75%,10.0,6.000000,3.00000,3.00000,18.000000,16.000000,6.000000,19.000000
max,10.0,7.000000,3.00000,5.00000,22.000000,20.000000,12.000000,23.000000

In [8]:
df.head(3)

,Time,Partidas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19
2,Palmeiras,10,5,3,2,18,12,6,18

In [12]:
df.tail(2)

,Time,Partidas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11